baseurl = "/brainstorm"
languageCode = "en-us"
title = "BrainBlog"
theme = "hugo-lithium"
googleAnalytics = "UA-11158994-2"
disqusShortname = "nopcode"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/braincode"

[params]
    author = "Roman Valls Guimera"
    description = "Braindumplings"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.15.9"
    highlightjsCDN = "https://cdnjs.cloudflare.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "https://cdnjs.cloudflare.com"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

